buildFuture = true
languageCode = 'en-us'
title = 'Nelson Tech Meetup'

[params]
description = 'A community of technology and knowledge workers in the Kootenays'
heroImage = 'images/kast-tech-meet-up-02.jpg'

[params.links]
facebook = 'https://www.facebook.com/groups/kootenayworkers'
github = 'https://github.com/nelson-tech-meetup'
newsletter = 'https://stats.sender.net/forms/eZP5Jb/view'
slack = 'https://join.slack.com/t/kootenaytech/shared_invite/zt-2gtyd3f1g-Ty3RV4zkgsQCInq5V6nRSg'

# GitHub repository for "Edit this page" links
[params.github]
branch = 'main'
repo = 'https://github.com/Nelson-Tech-Meetup/nelson-tech-meetup.github.io'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Meetings'
url = '/meetings/'
weight = 2

[module]
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"
