baseURL = 'https://example.org/'
buildFuture = true
languageCode = 'en-us'
title = 'Nelson Tech Meetup'

[params]
description = 'A community of technology and knowledge workers in the Kootenays'
heroImage = 'images/kast-tech-meet-up-02.jpg'

# GitHub repository for "Edit this page" links
[params.github]
repo = 'https://github.com/Nelson-Tech-Meetup/nelson-tech-meetup.github.io'
branch = 'main'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Meetings'
url = '/meetings/'
weight = 2

[module]
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"
